services:
  - type: web
    name: object-detection-backend
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    rootDirectory: backend
